"""Generate Markdown and self-contained HTML experiment reports."""

import html
import json
from typing import List, Optional, Tuple


# --------------------------------------------------------------------------- #
# Sparkline helpers (pure text/SVG, no dependencies)                          #
# --------------------------------------------------------------------------- #

def _text_sparkline(values: List[float], width: int = 40) -> str:
    """Return a Unicode block-bar sparkline string."""
    blocks = " ▁▂▃▄▅▆▇█"
    if not values:
        return ""
    lo, hi = min(values), max(values)
    span = hi - lo or 1e-9
    chars = []
    step = max(1, len(values) // width)
    for i in range(0, len(values), step):
        v = values[i]
        idx = int(((v - lo) / span) * (len(blocks) - 1))
        chars.append(blocks[idx])
    return "".join(chars)


def _svg_line(values: List[float], w: int = 400, h: int = 60, color: str = "#4f8ef7") -> str:
    """Return an inline SVG polyline."""
    if len(values) < 2:
        return ""
    lo, hi = min(values), max(values)
    span = hi - lo or 1e-9
    n = len(values)
    pts = []
    for i, v in enumerate(values):
        x = i / (n - 1) * w
        y = h - ((v - lo) / span) * (h - 4) - 2
        pts.append(f"{x:.1f},{y:.1f}")
    points = " ".join(pts)
    return (
        f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}" '
        f'xmlns="http://www.w3.org/2000/svg">'
        f'<polyline points="{points}" fill="none" stroke="{color}" stroke-width="2"/>'
        f"</svg>"
    )


# --------------------------------------------------------------------------- #
# Report dataclass                                                             #
# --------------------------------------------------------------------------- #

class ExperimentResult:
    def __init__(
        self,
        *,
        steps: int,
        drift_kind: str,
        drift_at: Optional[int],
        seed: int,
        model_name: str,
        detector_name: str,
        drift_events: List[Tuple[int, str]],         # (step, kind)
        snapshots: List[Tuple[int, float, float]],   # (step, acc, loss)
        final_accuracy: Optional[float],
        final_log_loss: Optional[float],
    ) -> None:
        self.steps = steps
        self.drift_kind = drift_kind
        self.drift_at = drift_at
        self.seed = seed
        self.model_name = model_name
        self.detector_name = detector_name
        self.drift_events = drift_events
        self.snapshots = snapshots
        self.final_accuracy = final_accuracy
        self.final_log_loss = final_log_loss


# --------------------------------------------------------------------------- #
# Markdown                                                                     #
# --------------------------------------------------------------------------- #

def to_markdown(result: ExperimentResult) -> str:
    acc_vals = [s[1] for s in result.snapshots]
    loss_vals = [s[2] for s in result.snapshots]

    lines = [
        "# DriftLens Lab — Experiment Report",
        "",
        f"| Parameter | Value |",
        f"|-----------|-------|",
        f"| Steps | {result.steps} |",
        f"| Drift kind | `{result.drift_kind}` |",
        f"| Drift at | {result.drift_at if result.drift_at is not None else '—'} |",
        f"| Seed | {result.seed} |",
        f"| Model | {result.model_name} |",
        f"| Detector | {result.detector_name} |",
        "",
        "## Metrics",
        "",
        f"- **Final rolling accuracy**: {result.final_accuracy:.4f}" if result.final_accuracy is not None else "- Final rolling accuracy: n/a",
        f"- **Final rolling log-loss**: {result.final_log_loss:.4f}" if result.final_log_loss is not None else "- Final rolling log-loss: n/a",
        "",
        "### Accuracy over time",
        "",
        f"```\n{_text_sparkline(acc_vals)}\n```",
        "",
        "### Log-loss over time",
        "",
        f"```\n{_text_sparkline(loss_vals)}\n```",
        "",
        "## Drift Events",
        "",
    ]

    if result.drift_events:
        lines.append("| Step | Kind |")
        lines.append("|------|------|")
        for step, kind in result.drift_events:
            lines.append(f"| {step} | `{kind}` |")
    else:
        lines.append("_No drift events detected._")

    lines += ["", "---", "_Generated by DriftLens Lab_"]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# HTML                                                                         #
# --------------------------------------------------------------------------- #

_CSS = """
body { font-family: system-ui, sans-serif; max-width: 860px; margin: 2rem auto; padding: 0 1rem; color: #222; }
h1 { color: #1a3a6e; }
h2 { color: #2d5086; border-bottom: 1px solid #cce; padding-bottom: .25rem; }
table { border-collapse: collapse; width: 100%; margin-bottom: 1rem; }
th, td { text-align: left; padding: .4rem .8rem; border: 1px solid #dde; }
th { background: #eef2fb; }
.metric-card { display: inline-block; background: #f4f7ff; border: 1px solid #cdd; border-radius: 6px; padding: .6rem 1.2rem; margin: .4rem .4rem .4rem 0; }
.metric-card .val { font-size: 1.6rem; font-weight: bold; color: #1a3a6e; }
.metric-card .lbl { font-size: .8rem; color: #666; }
.event-drift { color: #c0392b; font-weight: bold; }
.event-warning { color: #e67e22; }
code { background: #f0f0f0; padding: .1rem .3rem; border-radius: 3px; }
footer { margin-top: 2rem; font-size: .8rem; color: #999; }
"""

def to_html(result: ExperimentResult) -> str:
    acc_vals = [s[1] for s in result.snapshots]
    loss_vals = [s[2] for s in result.snapshots]
    steps_vals = [s[0] for s in result.snapshots]

    acc_svg = _svg_line(acc_vals, color="#4f8ef7")
    loss_svg = _svg_line(loss_vals, color="#e74c3c")

    drift_rows = ""
    for step, kind in result.drift_events:
        cls = "event-drift" if kind == "drift" else "event-warning"
        drift_rows += f"<tr><td>{step}</td><td class='{cls}'>{html.escape(kind)}</td></tr>\n"
    if not drift_rows:
        drift_rows = "<tr><td colspan='2'><em>No drift events detected.</em></td></tr>"

    acc_str = f"{result.final_accuracy:.4f}" if result.final_accuracy is not None else "n/a"
    loss_str = f"{result.final_log_loss:.4f}" if result.final_log_loss is not None else "n/a"
    drift_at_str = str(result.drift_at) if result.drift_at is not None else "—"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>DriftLens Lab Report</title>
<style>{_CSS}</style>
</head>
<body>
<h1>DriftLens Lab — Experiment Report</h1>
<table>
  <tr><th>Parameter</th><th>Value</th></tr>
  <tr><td>Steps</td><td>{result.steps}</td></tr>
  <tr><td>Drift kind</td><td><code>{html.escape(result.drift_kind)}</code></td></tr>
  <tr><td>Drift at</td><td>{drift_at_str}</td></tr>
  <tr><td>Seed</td><td>{result.seed}</td></tr>
  <tr><td>Model</td><td>{html.escape(result.model_name)}</td></tr>
  <tr><td>Detector</td><td>{html.escape(result.detector_name)}</td></tr>
</table>

<h2>Metrics</h2>
<div class="metric-card"><div class="val">{acc_str}</div><div class="lbl">Rolling Accuracy</div></div>
<div class="metric-card"><div class="val">{loss_str}</div><div class="lbl">Rolling Log-Loss</div></div>

<h2>Accuracy over time</h2>
{acc_svg}

<h2>Log-Loss over time</h2>
{loss_svg}

<h2>Drift Events</h2>
<table>
  <tr><th>Step</th><th>Kind</th></tr>
  {drift_rows}
</table>

<footer>Generated by <strong>DriftLens Lab</strong></footer>
</body>
</html>
"""


def write_report(result: ExperimentResult, path: str) -> None:
    """Write HTML or Markdown report depending on file extension."""
    import os
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    if path.endswith(".md"):
        content = to_markdown(result)
    else:
        content = to_html(result)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
